update dockerfile to avoid build error

diff --git a/dockerfiles/Dockerfile b/dockerfiles/Dockerfile
--- a/dockerfiles/Dockerfile
+++ b/dockerfiles/Dockerfile
@@ -11,7 +11,8 @@ RUN pip3 install planemo
 
 COPY dockerfiles/dummy_tool.xml /tmp/dummy_tool.xml
 
-RUN cd /tmp && planemo test --galaxy_root /galaxy /tmp/dummy_tool.xml
+# this may fail (and does fail for Galaxy 24.0.2, but it's ok - we only need to install dependencies)
+RUN cd /tmp && planemo test --galaxy_root /galaxy /tmp/dummy_tool.xml || echo planemo failed, but ok
 
 CMD ["bash"]
 
